tunnel: 4b9618b0-dda3-4c26-9ba5-9bc2443bff11
credentials-file: ~/.cloudflared/4b9618b0-dda3-4c26-9ba5-9bc2443bff11.json

ingress:
  - hostname: vpn.yofiproject.pro
    service: http://localhost:8080
  - service: http_status:404
