name: Cloudflared Tunnel

on:
  workflow_dispatch:   # bisa jalan manual dari tab Actions
  push:
    branches:
      - main

jobs:
  tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Setup credentials
        run: |
          mkdir -p ~/.cloudflared
          echo "${{ secrets.CLOUDFLARED_TUNNEL_CRED }}" > ~/.cloudflared/${{ secrets.CLOUDFLARED_TUNNEL_ID }}.json

      - name: Run tunnel
        run: |
          cloudflared tunnel run ${{ secrets.CLOUDFLARED_TUNNEL_ID }}
